pipeline {
    agent any
    stages {
        stage('deploy release candidate to staging') {
            when { tag "refs/tags/rc.*" }
            steps {
                build job: "dev-deploy/${env.BRANCH_NAME}",
                        propagate: true,
                        wait: true,
                        parameters: [[$class: 'StringParameterValue', name: 'IMAGE_TAG', value: "${BRANCH_NAME}"], [$class: 'StringParameterValue', name: 'ACCOUNT_ID', value: "staging_account_id"]]

            }
        }
        stage('deploy release to production') {
            when { tag "release.*" }
            steps {
                build job: "dev-deploy/${env.BRANCH_NAME}",
                        propagate: true,
                        wait: true,
                        parameters: [[$class: 'StringParameterValue', name: 'IMAGE_TAG', value: "${BRANCH_NAME}"], [$class: 'StringParameterValue', name: 'ACCOUNT_ID', value: "production_account_id"]]
            }
        }
        stage('verify release candidate') {
            when { tag "rc.*" }
            steps {
                build job: "dev-test/${env.BRANCH_NAME}",
                        propagate: true,
                        wait: true,
                        parameters: [[$class: 'StringParameterValue', name: 'TIER', value: "STAGING"], [$class: 'StringParameterValue', name: 'ACCOUNT_ID', value: "staging_account_id"]]

            }
        }
        stage('verify release') {
            when { tag "release.*" }
            steps {
                build job: "dev-test/${env.BRANCH_NAME}",
                        propagate: true,
                        wait: true,
                        parameters: [[$class: 'StringParameterValue', name: 'TIER', value: "PROD"], [$class: 'StringParameterValue', name: 'ACCOUNT_ID', value: "production_account_id"]]

            }
        }
        stage('Approve Release') {
            when {
                tag "rc.*"
            }
            steps {
                input "Tag release?"
                script {
                    tag_rc = VersionNumber([
                            versionNumberString: '${BUILD_DATE_FORMATTED, "yyyyMMdd"}.${BUILDS_TODAY}.${BUILD_NUMBER}',
                            versionPrefix      : 'release.'])
                    app = docker.image("simonjgould/hanzo-test-poll-api:${env.BRANCH_NAME}.latest")
                    docker.withRegistry('', 'docker-hub') {
                        app.push("${tag_rc}")
                    }
                }

                sh "git tag -a ${tag_rc} -m 'release'"
                withCredentials([[$class          : 'UsernamePasswordMultiBinding',
                                  credentialsId   : 'Git',
                                  usernameVariable: 'GIT_USERNAME',
                                  passwordVariable: 'GIT_PASSWORD']]) {
                    sh('chmod +x pipeline/tools/tag_script.sh')
                    sh("pipeline/tools/tag_script.sh $GIT_USERNAME $GIT_PASSWORD")
                }
            }
        }
    }
}